import duckdb
from uuid import UUID
from dags.brewery import generate_aggregate_query, generate_transform_query


class TestGenerateAggregateQuery:
    def test_query(self):
        conn = duckdb.connect(":memory:")
        query = generate_aggregate_query("tests/dags/sample/raw.json", "read_json_auto")
        conn.execute(query)
        expected_output = [
            {
                "brewery_type": "micro",
                "country": "United States",
                "state": "Wisconsin",
                "city": "Mount Pleasant",
                "count_star()": 1,
            },
            {
                "brewery_type": "micro",
                "country": "United States",
                "state": "Texas",
                "city": "Austin",
                "count_star()": 1,
            },
            {
                "brewery_type": "micro",
                "country": "United States",
                "state": "Oklahoma",
                "city": "Norman",
                "count_star()": 1,
            },
            {
                "brewery_type": "large",
                "country": "United States",
                "state": "Oregon",
                "city": "Portland",
                "count_star()": 1,
            },
            {
                "brewery_type": "large",
                "country": "United States",
                "state": "Oregon",
                "city": "Bend",
                "count_star()": 3,
            },
            {
                "brewery_type": "large",
                "country": "United States",
                "state": "Idaho",
                "city": "Boise",
                "count_star()": 1,
            },
            {
                "brewery_type": "large",
                "country": "United States",
                "state": "Colorado",
                "city": "Denver",
                "count_star()": 1,
            },
            {
                "brewery_type": "large",
                "country": "United States",
                "state": "California",
                "city": "San Diego",
                "count_star()": 1,
            },
        ]

        results = conn.fetchall()
        columns = [desc[0] for desc in conn.description]
        dict_results = [dict(zip(columns, row)) for row in results]

        assert dict_results == expected_output


class TestGenerateTransformedQuery:
    def test_query(self):
        conn = duckdb.connect(":memory:")
        query = generate_transform_query("tests/dags/sample/raw.json", "read_json_auto")
        conn.execute(query)
        expected_output = [
            {
                "id": UUID("5128df48-79fc-4f0f-8b52-d06be54d0cec"),
                "name": "(405) Brewing Co",
                "brewery_type": "micro",
                "address_1": "1716 Topeka St",
                "address_2": None,
                "address_3": None,
                "city": "Norman",
                "state_province": "Oklahoma",
                "postal_code": "73069-8224",
                "country": "United States",
                "longitude": "-97.46818222",
                "latitude": "35.25738891",
                "phone": "4058160490",
                "website_url": "http://www.405brewing.com",
                "state": "Oklahoma",
                "street": "1716 Topeka St",
            },
            {
                "id": UUID("9c5a66c8-cc13-416f-a5d9-0a769c87d318"),
                "name": "(512) Brewing Co",
                "brewery_type": "micro",
                "address_1": "407 Radam Ln Ste F200",
                "address_2": None,
                "address_3": None,
                "city": "Austin",
                "state_province": "Texas",
                "postal_code": "78745-1197",
                "country": "United States",
                "longitude": None,
                "latitude": None,
                "phone": "5129211545",
                "website_url": "http://www.512brewing.com",
                "state": "Texas",
                "street": "407 Radam Ln Ste F200",
            },
            {
                "id": UUID("34e8c68b-6146-453f-a4b9-1f6cd99a5ada"),
                "name": "1 of Us Brewing Company",
                "brewery_type": "micro",
                "address_1": "8100 Washington Ave",
                "address_2": None,
                "address_3": None,
                "city": "Mount Pleasant",
                "state_province": "Wisconsin",
                "postal_code": "53406-3920",
                "country": "United States",
                "longitude": "-87.88336350209435",
                "latitude": "42.72010826899558",
                "phone": "2624847553",
                "website_url": "https://www.1ofusbrewing.com",
                "state": "Wisconsin",
                "street": "8100 Washington Ave",
            },
            {
                "id": UUID("ef970757-fe42-416f-931d-722451f1f59c"),
                "name": "10 Barrel Brewing Co",
                "brewery_type": "large",
                "address_1": "1501 E St",
                "address_2": None,
                "address_3": None,
                "city": "San Diego",
                "state_province": "California",
                "postal_code": "92101-6618",
                "country": "United States",
                "longitude": "-117.129593",
                "latitude": "32.714813",
                "phone": "6195782311",
                "website_url": "http://10barrel.com",
                "state": "California",
                "street": "1501 E St",
            },
            {
                "id": UUID("6d14b220-8926-4521-8d19-b98a2d6ec3db"),
                "name": "10 Barrel Brewing Co",
                "brewery_type": "large",
                "address_1": "62970 18th St",
                "address_2": None,
                "address_3": None,
                "city": "Bend",
                "state_province": "Oregon",
                "postal_code": "97701-9847",
                "country": "United States",
                "longitude": "-121.281706",
                "latitude": "44.08683531",
                "phone": "5415851007",
                "website_url": "http://www.10barrel.com",
                "state": "Oregon",
                "street": "62970 18th St",
            },
            {
                "id": UUID("e2e78bd8-80ff-4a61-a65c-3bfbd9d76ce2"),
                "name": "10 Barrel Brewing Co",
                "brewery_type": "large",
                "address_1": "1135 NW Galveston Ave Ste B",
                "address_2": None,
                "address_3": None,
                "city": "Bend",
                "state_province": "Oregon",
                "postal_code": "97703-2465",
                "country": "United States",
                "longitude": "-121.3288021",
                "latitude": "44.0575649",
                "phone": "5415851007",
                "website_url": None,
                "state": "Oregon",
                "street": "1135 NW Galveston Ave Ste B",
            },
            {
                "id": UUID("e432899b-7f58-455f-9c7b-9a6e2130a1e0"),
                "name": "10 Barrel Brewing Co",
                "brewery_type": "large",
                "address_1": "1411 NW Flanders St",
                "address_2": None,
                "address_3": None,
                "city": "Portland",
                "state_province": "Oregon",
                "postal_code": "97209-2620",
                "country": "United States",
                "longitude": "-122.6855056",
                "latitude": "45.5259786",
                "phone": "5032241700",
                "website_url": "http://www.10barrel.com",
                "state": "Oregon",
                "street": "1411 NW Flanders St",
            },
            {
                "id": UUID("9f1852da-c312-42da-9a31-097bac81c4c0"),
                "name": "10 Barrel Brewing Co - Bend Pub",
                "brewery_type": "large",
                "address_1": "62950 NE 18th St",
                "address_2": None,
                "address_3": None,
                "city": "Bend",
                "state_province": "Oregon",
                "postal_code": "97701",
                "country": "United States",
                "longitude": "-121.2809536",
                "latitude": "44.0912109",
                "phone": "5415851007",
                "website_url": None,
                "state": "Oregon",
                "street": "62950 NE 18th St",
            },
            {
                "id": UUID("ea4f30c0-bce6-416b-8904-fab4055a7362"),
                "name": "10 Barrel Brewing Co - Boise",
                "brewery_type": "large",
                "address_1": "826 W Bannock St",
                "address_2": None,
                "address_3": None,
                "city": "Boise",
                "state_province": "Idaho",
                "postal_code": "83702-5857",
                "country": "United States",
                "longitude": "-116.202929",
                "latitude": "43.618516",
                "phone": "2083445870",
                "website_url": "http://www.10barrel.com",
                "state": "Idaho",
                "street": "826 W Bannock St",
            },
            {
                "id": UUID("1988eb86-f0a2-4674-ba04-02454efa0d31"),
                "name": "10 Barrel Brewing Co - Denver",
                "brewery_type": "large",
                "address_1": "2620 Walnut St",
                "address_2": None,
                "address_3": None,
                "city": "Denver",
                "state_province": "Colorado",
                "postal_code": "80205-2231",
                "country": "United States",
                "longitude": "-104.9853655",
                "latitude": "39.7592508",
                "phone": "7205738992",
                "website_url": None,
                "state": "Colorado",
                "street": "2620 Walnut St",
            },
        ]
        results = conn.fetchall()
        columns = [desc[0] for desc in conn.description]
        dict_results = [dict(zip(columns, row)) for row in results]

        assert dict_results == expected_output
